# Site settings
title: Clean Blog
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/"
url: "http://yourdomain.com"
twitter_username: ChristianMeter
github_username:  n2o
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
