# Site settings
title: Ho-Ho-Hearthstone
email: christian.meter@uni-duesseldorf.de
description: "Tournament"
baseurl: ""
url: "https://ho-ho-hearthstone.github.io"
twitter_username:
github_username:
facebook_username:  events/352682484900486/?ref_dashboard_filter=upcoming

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
